== Terms and definitions



For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.


&#9679; coordinate reference system ::

 coordinate system that is related to the real world by a datum term name (source: ISO 19111)

&#9679; coverage ::

 feature that acts as a function to return values from its range for any direct position within its spatiotemporal domain, as defined in OGC Abstract Topic 6

&#9679; record ::

 atomic unit of information of a catalogue that is used to provide information about a particular resource


&#9679; OpenAPI Document ::

 A document (or set of documents) that defines or describes an API. An OpenAPI definition uses and conforms to the OpenAPI Specification (https://www.openapis.org)


&#9679; Web API  ::

 API using an architectural style that is founded on the technologies of the Web [source: OGC API - Features - Part 1: Core]

NOTE: See Best Practice 24: Use Web Standards as the foundation of APIs (W3C Data on the Web Best Practices) for more detail.

===	Abbreviated terms

* *API* Application Programming Interface
* *CORS* Cross-Origin Resource Sharing
* *OGC* Open Geospatial Consortium
