[[Introduction]]
== Introduction

This Engineering Report (ER) summarizes the main achievements of the July 2021 OGC API Virtual Code Sprint, conducted from July 21st to July 23rd. The sprint had been organized to advance the development of draft standards of OGC APIs for Records, Coverages and Processes. Sprint participants prototyped implementations of the draft standards, validating the requirements and providing feedback so that the draft standards could be improved.

An OGC Code Sprint is a collaborative and inclusive event driven by innovative and rapid programming with minimal process and organization constraints to support the development of new applications and open standards. OGC Code Sprints experiment with emerging ideas in the context of geospatial standards, help improve interoperability of existing standards by experimenting with new extensions or profiles, and are used for building proofs of concept for other OGC Innovation Program initiatives, or to support OGC Standards Program activities.
