[[Discussion]]
== Discussion

This sections provides a summary of the discussion.

=== Potential relationship between STAC and OGC API - Records

The sprint participants discussed the potential relationship between STAC and OGC API - Records, in order to identify opportunities for alignment. This subsection summarises that discussion.

The sprint participants noted that there had been previous discussions between OGC staff and the STAC community about the possibility of bringing the STAC API into the OGC's standardization process. This was partly because the STAC API is an extension of OGC API - Features - Part 1: Core. The current thinking is to submit STAC into the standardization process as a candidate OGC Community Standard. That would require STAC to be stable, at version 1.0 at least.

Some of the opportunities for alignment between STAC and OGC API - Records are static equivalents for Collections and Records. The sprint participants noted that, in a previous discussion, there was an observation that there is a need for a 'Dataset Record'. A 'Record' would be a flexible and generic concept, whereas a Dataset Record would represent dataset metadata such as in the context of ISO 19115. The grouping would be the Collection. With these concepts in place, it would potentially be possible to have STAC as a Record or an extension of OGC API - Records.

The sprint participants noted that in OGC API - Records, in contrast to STAC, the actual Record description is distinct from the API. The Record description is loosely bound to the API in OGC API - Records, for example, there is no requirement for the record to be encoded in GeoJSON as other encodings (e.g. ATOM) are allowed. The Record is also not bound to a particular dataset or asset. There is an expectation that developers would take the Record and enrich the content to suit specific needs. There was an observation made that it would benefit developers to extract the description of the Record content model and make it more standard-alone on either the specification document as a building block or in an accompanying document such as user guide.

What is the distinction between the STAC Catalog and the STAC Collections specifications? The STAC Catalog is a JSON file of links that provides a structure to organize and browse STAC Items. The STAC Collection is an extension of the STAC Catalog with additional information that describes STAC Items that fall within the Collection. The STAC Catalog specification is therefore less tied to the API. It is just a structured concept that says "this links to more items". If you have millions of records, instead of placing them in a single collection, the catalog lets you break them up in arbitrary ways. The approach is based on OGC API - Features, and so a STAC Collection can be served as a Collection from an OGC API - Features implementation.

The Records API does not do anything different to what the Features API does. That is, the two APIs are consistent. This suggests that the biggest need is for the Dataset Collection, with the fields in the collection clearly defined. This is necessary because Collection is non-GeoJSON, whereas Record is GeoJSON. They should translate between each other easily. This could, for instance, lead to a static Features API involving a series of files in a Cloud Storage resource. The sprint participants observed that, from a Meteorological perspective, it would be useful to have a static API that provides access to a series of files.

STAC inherits from an OGC API - Features collection, but ideally the preference would be to inherit from a Dataset Collection. So potentially there could be two separate representations of the collection, at different levels of the API hierarchy, using an 'alternate' relation type to provide links to the two different representations. The sprint participants suggested that Part 1 should be more generic and then consider the Dataset Collection for Part 2. Support for datasets should be optional and could be based on ISO 19115-1 metadata. This could then lead to a Part 3 that focuses on STAC. The work on STAC should not start until the Part 1 is stable.

There was also discussion about the structure of the Part 1 document, including whether some conformance classes (e.g. sort by) should be moved to OGC API - Features. This also included consideration of where a section describing the Collection could be placed in OGC API - Records - Part 1: Core. This capability would facilitate the creation of static catalogs. A static catalog would offer value to some user needs. Such a capability could have more utility and wider uptake if included in OGC API - Features, and possibly in  the long term it could be part of OGC API - Common. The capability could also be specified in OGC API - Records and still have utility in OGC API - Features. In OGC API - Features, by default, every API implementing the standard will provide access to a single dataset.

=== Should OGC API - Records support the OpenSearch Syndication Protocol?

The sprint participants discussed whether the OpenSearch Syndication Protocol is still being used and whether it is still relevant. The discussion was in part triggered by the migration of the OpenSearch Syndication Protocol from its previous home of opensearch.org to a https://github.com/dewitt/opensearch[personal GitHub repository]. OpenSearch is a registered trademark of Amazon and now has been repurposed to https://opensearch.org[refer] to an open source search and analytics suite. To disambiguate between the two OpenSearch initiatives, an https://opensearch.org/disambiguation.html[explanatory web page] has been created. Maintainers of the OpenSearch Syndication Protocol also provide https://github.com/dewitt/opensearch#how-is-it-related-to-the-opensearch-software-project[their own] disambiguation. The sprint participants observed that, after supporting the OpenSearch Protocol for a number of years, the protocol was https://blog.mozilla.org/addons/2019/10/15/search-engine-add-ons-to-be-removed-from-addons-mozilla-org/[no longer supported] in add-ons of the Mozilla Firefox web browser.

The OpenSearch Syndication Protocol is referenced by a number of OGC Standards, namely https://portal.ogc.org/files/?artifact_id=56866[OGC® OpenSearch Geo and Time Extensions (OGC 10-032)], http://docs.opengeospatial.org/is/13-026r9/13-026r9.html[OGC OpenSearch Extension for Earth Observation (OGC 13-026r9)], https://docs.opengeospatial.org/is/17-047r1/17-047r1.html[OGC OpenSearch-EO GeoJSON(-LD) Response Encoding Standard (OGC 17-047r1)], and https://docs.ogc.org/is/17-003r2/17-003r2.html[OGC EO Dataset Metadata GeoJSON(-LD) Encoding Standard (17-003r2)]. The OpenSearch Syndication Protocol defines an XML "description" format for search services to describe how to send them search queries. If the search service formats the results in RSS or ATOM the results from multiple services can be merged into a single listing. The protocol is actively used in the Earth Observation community, for example, at the European Space Agency (ESA) and the US National Aeronautics and Space Administration (NASA), possibly because another protocol has not emerged to fill this role.


The draft OGC API - Records - Part 1: Core standard currently includes a conformance class for the OpenSearch Syndication Protocol. The sprint participants recommended that the conformance class be removed out of the draft OGC API - Records - Part 1: Core standard and be considered for a future extension. Specifying the conformance class in a separate extension would allow the conformance class to be easily deprecated or renamed in the future without affecting the rest of OGC API - Records.

=== Coverage Processing in OGC API - Processes

There was a discussion to explore whether a new language could be developed to support the analysis of coverages in implementations of OGC API - Processes. Such a language would address similar needs to those addressed by the Web Coverage Processing Service (WCPS). There was concern that WCPS could be too complex to use, hence the need for a simpler alternative. Having a simpler alternative would allow client applications to specify the language that they are using in a request. The sprint participants noted that currently several products use raster algebra to support analysis and filtering, however, the products do not appear to share a common language for expressing the raster algebra.

The sprint participants expressed an interest in having a consistent syntax for expressions. The new language or syntax for describing coverage analysis would need to be able to access information about the coverage at multiple levels e.g. at coverage level, band level and at pixel level. The expressivity of the language was therefore identified as a key consideration, on a simplicity spectrum, a single link expression would be the easiest to implement but would be limited in its ability to express analysis. In contrast, a procedural language would be more expressive and allow the description of more complex analysis.


=== Supporting ISO 19115-1:2014 and ISO 19115:2003 in OGC API - Records

There are also several organizations that have established infrastructure that relies on ISO 19115-1:2014, https://www.iso.org/standard/26020.html[ISO 19115:2003] and their profiles. Examples of profiles of ISO 19115-1:2014 include https://gwg.nga.mil/documents/NMF_v1_final.doc[NSG Metadata Foundation (NMF)] and https://portal.dgiwg.org/files/67565[DGIWG Metadata Foundation (DMF)]. Examples of profiles of ISO 19115:2003 include the https://inspire.ec.europa.eu/documents/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-1[INSPIRE Metadata Implementing Rules] and https://www.anzlic.gov.au/sites/default/files/files/anzlic_metadata_profile_v1_1.pdf[ANZLIC Metadata Profile]. (It should be noted that the ANZLIC profile of ISO19115 has been deprecated by anzlic and replaced by ISO19115-1:2014/Add-1:2118 and is seeing broad use.) The sprint participants noted that one of the challenges of the OGC API - Records SWG will be to design the API in such a way that allows for the publication of metadata encoded according to ISO 19115-1 or its profiles.

The sprint participants confirmed that OGC API - Records can return records representing metadata fields from ISO 19115-1:2014, which are encoded according to the schemas specified in https://www.iso.org/standard/32579.html[ISO/TS 19115-3:2016]. Similarly,  OGC API - Records can return records representing metadata fields from ISO 19115:2003, which are encoded according to the schemas specified in https://www.iso.org/standard/32557.html[ISO/TS 19139:2007]. This is achieved through Content Negotiation. For example, the following GET request retrieves a JSON encoded metadata record from a pycsw instance deployed for the EO Exploitation Platform Common Architecture (EOEPCA). The response is as shown in <<annex_jsonexample>>.

https://resource-catalogue.demo.eoepca.org/collections/metadata:main/items/S2A_MSIL1C_20200930T092031_N0209_R093_T34SDF_20200930T105731.SAFE?f=json

The same metadata record can be retrieved encoded in XML conforming to ISO 19115-3 through the request below. The response is as shown in <<annex_iso19115example>>.

https://resource-catalogue.demo.eoepca.org/collections/metadata:main/items/S2A_MSIL1C_20200930T092031_N0209_R093_T34SDF_20200930T105731.SAFE?f=xml

The examples above highlight that one of the reasons why the Records API has a Record model is to allow an implementation of OGC API - Records to query across any metadata standard that can be mapped to the Record model. If a data publisher has a catalogue that is based on ISO 19115-3, then all they need to do is to map their schema to the model in OGC API - Records. Another option is to make a mapping between ISO to the Record model in OGC API - Records. An example of such a mapping was developed during the code sprint and is available on the sprint's https://github.com/opengeospatial/ogcapi-code-sprint-2021-07/blob/main/mappings/ISO19115-3_Mappings.md[GitHub repository] and is also presented in <<annex_mappings>>. As the example listings shown above indicate, there is a need to specify which XML profile to retrieve the metadata in. This is something that could be proposed as a new conformance class in a new OGC API - Records extension or profile standard. The Content Negotiation mechanism would be designed to allow the use of the `profile` mechanism in media types or a `schema` query parameter to identify the schema to use.

=== Lessons Learnt

Towards the end of the sprint, participants held a discussion on the lessons learnt from the initiative. A summary of the lessons identified by the sprint participants is presented below:

* RecordsAPI: The relationship with STAC was clarified in this sprint. The direction of the RecordsAPI is aligning more with STAC.
* RecordsAPI: Crosswalk aligned ISO 19115-3 with the OGC Record.
* There may be a little bit of work to do in aligning satellite imagery support between RecordsAPI and STAC.
* Clarity on what it means to have an ISO 19115 conformance class in OGC API - Records.
* The change with OpenSearch.org introduces challenges in terms of usage/licence. Will mean change requests for existing OGC OpenSearch standards.
* OpenSearch is still an active thing in OGC. It will be placed in an extension of OGC API - Records and not the Core.
* OGC Member Meeting in September 2021 (Metadata Adhoc) will have a session on tackling metadata issues. It's linked to the Singapore Geo Festival.
* Lots of implementations of OGC API - Processes provides confidence that it works.
* The Spring work will help develop Guides.
* OGC API - Processes is sufficiently different from WPS
* The use of JSON Schema to describe inputs and outputs is going to be great for uptake.
* There is an increasing need for Best Practices and Profiles. e.g. Routing, Maps, NDVI, ...
* OGC API - Processes weather toolbox (we're starting to think about this in MetOceanDWG)
