= Immediate Lessons and Next Steps

== Immediate Lessons

* RecordsAPI: The relationship with STAC was clarified in this sprint. The direction of the RecordsAPI is aligning more with STAC.
* RecordsAPI: Crosswalk aligned ISO19115-3 with the OGC Record.
* There may be a little bit of work to do in aligning satellite imagery support between RecordsAPI and STAC.
* Clarity on what it means to have an ISO 19115 extension. The pycsw/pygeoapi? demo showed how.
* The change with OpenSearch.org introduces challenges in terms of usage/licence. Will mean change requests for existing OGC OpenSearch standards.
* OpenSearch is still an active thing in OGC. It will be placed in an extension of OGC API - Records and not the Core.
* OGC Member Meeting in September 2021 (Metadata Adhoc) will have a session on tackling metadata issues. It's linked to the Singapore Geo Festival.
* Lots of implementations of OGC API - Processes provides confidence that it works.
* The Spring work will help develop Guides.
* OGC API - Processes is sufficiently different from WPS
* The use of JSON Schema to describe inputs and outputs is going to be great for uptake.
* There is an increasing need for Best Practices and Profiles. e.g. Routing, Maps, NDVI, ...
* OGC API - Processes weather toolbox (we're starting to think about this in MetOceanDWG)


== Next Steps for the Innovation Program

* Development of Developer Guides (e.g. Spring, Python, nodeJS etc), including around toolchains
* Some experimentation on Workflows (OGC API - Processes - Part 3), covering chaining
* The filtering and coverage processing. Filtering at the metadata leveel and at the coverage cell value level
* GeoDataClass (aka StylableLayerSet) concept in relation to discovering Processes & Data that can be used together, including in the context of Workflows
* Some along the workflow of a search process (e.g. ISO 19115, STAC, etc).

== Next Steps for the Standards Program

* ETS of OGC API - Coverages, Records
* Merge the work done on the openapi schema for the Coverages API
* Transactions on OGC API - Processes (Part 2)
* OGC API - Processes - Part 3: Workflows & Chaining

